apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bsm-api-deployment
  labels:
    app: bsm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bsm-api
  template:
    metadata:
      labels:
        name: bsm-api
    spec:
      containers:
      - name: app1
        image: gcr.io/my-project-d3-240508/app1:latest
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=my-project-d3-240508:us-central1:my-project-d3-240508-db-instance20=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
